/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm;

import org.junit.Test;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        fail("unexpected error");
    }
}
